### ISSUE TITLE
What does option "Fit to edges only inside selected screen area" actually do?

### ISSUE THREAD

**Issue by Fat-Zer** [lxqt/screengrab#142]
What does option "Fit to edges only inside selected screen area" actually do? It's quite obscure from the title and it would be helpful to have a verbose tooltip describing it.

Also as mentioned bellow it doesn't actually work correct.

**Comment by tsujan** [comment]
It should be for multiple screens, although it doesn't work properly -- a reminder for me to look into it if I find time.

**Comment by tsujan** [comment]
This isn't a bug but a hidden but smart feature. I understood it only by reading the code; the GUI explanation is so poor that it can hardly be called an "explanation".

@Fat-Zer You could see the feature by selecting an area *near vertical and/or horizontal lines that have enough contrast with their backgrounds* and then right click into it. If the checkbox is checked and your selected area is a little bigger (less than 20 px), it'll got smaller to fit the lines. If it's unchecked and your selected area is a little smaller, it'll got bigger to fit. A screenshot that's easily taken by using this method:

![fitting](https://user-images.githubusercontent.com/981076/70865686-769f2f80-1f75-11ea-84a0-e10ef34f5bf2.png)

I keep this open until a real explanation is added to the GUI -- maybe a big tooltip or, rather, a "WhatsThis" (because tooltips disappear).
