### ISSUE TITLE
Clicking image opens inexisting path

### ISSUE THREAD

**Issue by stefonarch** [lxqt/screengrab#294]
Just by case I clicked the image shown by Screengrab and LXimage-qt opens , but a non existing path, this happens also with default settings:

![screengrab](https://user-images.githubusercontent.com/10681413/160925986-f64076fe-cc46-4325-bccc-2037ba4f91ef.png)

##### Steps to Reproduce (for bugs)

1. Take a screenshot
2. Click the shown image

##### Context

Actually this could be quite useful, instead of using the dropdown and select.

* Distribution & Version:  git and arch

**Comment by tsujan** [comment]
Strange! I remember that I double clicked the view to open the image. False memory? I confirm that double clicking doesn't work (anymore?).

**Comment by tsujan** [comment]
OK, it was false memory. The code shows that it should have never worked because the temporary image is deleted as soon as the default app is launched.

Will try to fix it.

**Comment by stefonarch** [comment]
I've seen those random file names before somewhere with screengrab, but don't remember atm.

> Will try to fix it.

Thanks and good luck :)

**Comment by tsujan** [comment]
> Thanks and good luck :)

Thank YOU! I don't know how you find these hidden bugs but, when I ask you to test something, I'm sure that you won't miss probable issues that I may have missed — and that's why I ask *you*.

**Comment by tsujan** [comment]
I think I've fixed all problems related to calling of external apps (→ https://github.com/lxqt/screengrab/pull/298); requested a review from you.

BTW, I found out that I didn't have a false memory — actually, I never have ;) I didn't search for the reason why double clicking worked before; more than one reason may exist and it might haven't worked with all apps.

**Comment by tsujan** [comment]
Found the reason why it worked before (and still works for others). `xdg-open` exits on launching the default app after applying https://gitlab.freedesktop.org/luis-pereira/xdg-utils/-/commit/d2adf5efdc259a63028f8d4f21569c1557b8cfff (see https://github.com/lxqt/libqtxdg/issues/264), while it didn't exit without that patch.

That patch has no problem though. Starting an attached process and waiting for its `QProcess::finished()` signal was a wrong design of Sccreengrab, especially when that process was `xdg-open` (fixed in https://github.com/lxqt/screengrab/pull/298). That design was the source of troubles with single-instance apps too.
