### ISSUE TITLE
ScreenGrab crashes my laptop when I press PrntScr

### ISSUE THREAD

**Issue by Requiem53** [lxqt/screengrab#320]
When I press PrntScr on my laptop. It opens a lot of Screengrab windows (reaches above 30) and effectively freezing my laptop.

##### Expected Behavior

I expect that ScreenGrab just opens one window for ScreenGrab but instead it opens multiple and as far I know, it just keeps opening and opening new windows. I think ScreenGrab registers my PrntScr multiple times. It should only listen to the button press once.

##### Current Behavior

Pressing PrintScr opens a lot of ScreenGrab windows and freezing my laptop.

##### Possible Solution

It should only listen to me pressing PrntScr once to prevent multiple instances opening a the same time. Also, at least the option to unbind PrntScr to ScreenGrab.

##### Context

I lose all my work the moment I accidentally press PrntScr because I have to force shutdown my laptop.

##### System Information
I use the latest LTS version of Lubuntu and on a really old laptop.

**Comment by tsujan** [comment]
`PrntScr` isn't registered by ScreenGrab but by the shortcut manager you use (`lxqt-globalkeys`, openbox or both). So, this can't be a problem in ScreenGrab.

Although the issue is closed, you could add more comments to this page. Finding the cause requires more info — especially the system information that was requested at the end of the issue template.
