### ISSUE TITLE
It belong to LXQt; doesn't it?

### ISSUE THREAD

**Issue by tsujan** [lxqt/screengrab#83]
The answer is "it does" but, as a newcomer to screengrab, it's a bit confusing to me because (1) https://github.com/DOOMer/screengrab exists, (2) that URL is used for PRs and should be changed manually every time, and (3) things like this exist: https://aur.archlinux.org/packages/screengrab

I think this may be confusing to distros too. If screengrab belongs to LXQt, then https://github.com/DOOMer/screengrab should be removed. If that page isn't going to be removed, the name should be changed (to lxqt-grab, for example).

**Comment by agaida** [comment]
Right - the original project and the original author is doomer - and nobody really cares about screengrab that much as long it was forked into QtDesktop that much about.

**Comment by agaida** [comment]
Hmm, maybe we should ask polite and invite him - would be fine for me to aviod all the hassle

**Comment by yan12125** [comment]
The project description of this repo currently reads - 
```
Crossplatform tool for fast making screenshots. https://github.com/DOOMer/screengrab
```
I think the link should be updated?

**Comment by agaida** [comment]
yes, please

**Comment by yan12125** [comment]
Seems I don't have the permission to do that - no "Edit" button there. Could you modify it?

**Comment by agaida** [comment]
done

**Comment by jubalh** [comment]
would be nice if we could solve this without renaming to `lxqt-grab` so we can stay with current packages ;) *lazymode*

maybe we can convince doomer to configure that his repo forwards to this. github supports that.

**Comment by agaida** [comment]
is changing a VCS line really that hard? - and yes, it would be nice to have @doomer here and active :)

**Comment by jubalh** [comment]
> is changing a VCS line really that hard? 
what are you talking about?

**Comment by agaida** [comment]
why would you like to rename screengrab? Where is the problem?

**Comment by tsujan** [comment]
> why would you like to rename screengrab? Where is the problem?

Either we should rename it or the original author should remove his repository, otherwise the problems I mentioned above will happen. Since the original author doesn't respond, there remains only one option, IMO.

I propose "LXQtGrab" or "LXQtScreenshot".

**Comment by tsujan** [comment]
If LXDE isn't going to survive, "LXGrab" will be a good name too, although, IMO, it'll be good also with a surviving LXDE -- we have at least an equal right to the prefix "LX" ;)

**Comment by agaida** [comment]
erm - only one remark - of course we could rename the repo - but that wouldn't change nothing - the only thing we could do is to delete our repo and create it from the scratch - loosing history and so on included. Do we really want that - it would be the hard and not fair way to get rid of the fork marker - the only other way is to talk with @doomer

**Comment by jubalh** [comment]
> why would you like to rename screengrab? Where is the problem?

Im *against* renaming.


> the only thing we could do is to delete our repo and create it from the scratch

we would not loose history. the history is contained in git ;) @tsujan approach would just mean not having the link to the original one, and a new name.

@tsujan I think most downstream will see that there is a more active repo and a less active one. plus we announced it on our website, so distributions will pick this up.
there might be the problem of users creating issues at the wrong repo though, thats right.

doomer would not have to *remove* his repo, but just link to this one, github has this functionality since its very common case.

**Comment by agaida** [comment]
@jubalh - erm - bugs etc - and these things are not in the repo. Also called "classical lock-in"

**Comment by agaida** [comment]
god damn - but it doesn't solve the problem @tsujan wanted to solve :D

**Comment by agaida** [comment]
and my favoured outcome would be: Being the main repo **and** having @DOOMer on board

**Comment by tsujan** [comment]
Anyhow, please note that, after a while, LXQt's screengrab might become so different from the original screengrab that this situation couldn't continue. Since, in that time, we'll have more reports, we could only pray for DOOMer's presence and agreement (and I never pray).

**Comment by agaida** [comment]
we will find a solution

**Comment by jubalh** [comment]
When I packaged screengrab, I had a private conversation with agaida in which I asked:
What is the situation of screengrab? We took that over now? - Yes.

For me this means that it now belongs to us, with approval of the orignal maintainer. So it's not a fork with the same name but the coninuation of the project. Which also means since the orignal maintainer approved this, that he can be asked to forward the repo to ours.

I tried to find out at that point, before releasing it, what state we are in.
If that is the state then all is fine.

There are various projects on GitHub how have a repo at the original authors and a fork that continued, and always distributions need to take awareness of this and use the new place as a reference. Of course it's nice if the original resources links to the new one or has a note in the readme etc.

In any case I think the current situation is fine. The only way a problem can occur is if doomler decides to continue to work on screengrab, and base it of on the last state of his own repo and continue only there. Which is probably highly unlikely.

Like I sais we announced the taking over of screengrab on the website, and people who search GitHub can see that there are newer commits here than there.

In my opinion everything is "ok" and would be better if the original repo now links to ours.

But renaming seems very strange at this point. It should have either be done when forking or latest before releasing.

**Comment by jubalh** [comment]
I'm glad @tsujan.

**Comment by agaida** [comment]
@tsujan @jubalh @DOOMer - disconnected - @DOOMer, if you want to join us or would be so kind to allow us to be the root repo, please ping me. Thanks.

**Comment by agaida** [comment]
ok - i know, it doesn't solve all issues, but the very most of them.
